apiVersion: v1
kind: Service
metadata:
 annotations:
   kubernetes.io/elb.class: union
   kubernetes.io/elb.id: 46b2e252-b789-47cd-b8fc-8f6098ac4017 
 labels:
   app: lo2fe
 name: lo2fe
spec:
 loadBalancerIP: 90.84.195.132 # IP address of the an ELB service in a public
 ports:
 - name: lo2fe0
   port: 1880 # Cluster virtual IP address access port, which has
   protocol: TCP
   targetPort: 1880 # Container port set on the CCE console.
 selector:
   app: lo2fe
 type: LoadBalancer # The EIP must be based on an NodePort service.

